// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"database/sql"
)

type Comment struct {
	ID        int32
	UserID    int32
	Comment   string
	CreatedAt sql.NullTime
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}
