// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int32
	UserID    int32
	Comment   string
	CreatedAt sql.NullTime
}

type CommentReaction struct {
	ID        int32
	CommentID int32
	UserID    int32
	Reaction  int16
	CreatedAt time.Time
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}
